
spring:
  batch:
    job:
      enabled: true      # CommandLineRunner 설정 해제 .
    jdbc:
      table-prefix: SMB_
      platform: sqlite
      initialize-schema: embedded


logging:
  config: 'classpath:logback-spring.xml'
        